version: "3.9"

services:
  resource-service:
    build: ./server
    ports:
      - "5002:5002"
    env_file:
      - ./server/.env
    container_name: hw-resource-service

  frontend:
    build: ./client
    container_name: hw-resource-client
    ports:
      - "3002:80"
    depends_on:
      - resource-service

